# Site settings
title: SmnE
header-img: img/home-bg.jpg
email: smn.egli+githubpages@gmail.com
copyright_name: Simon Egli
description: "Welcome to my thoughts"
baseurl: "/deadolus.github.io"
url: "https://deadolus.github.io"
twitter_username: smnegli
github_username:  deadolus
facebook_username:  
email_username:  smn.egli+githubpages@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
